name: Update stock data

on:
  schedule:
    # каждый день в 08:00 UTC (13:00 Almaty)
    - cron: '0 8 * * *'
  workflow_dispatch:     # ручной запуск

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests pandas

      - name: Update data
        run: |
          python update_data.py

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n $(git status --porcelain) ]]; then
            git add data/stocks.csv
            git commit -m "Auto-update stock data"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi